//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace Etupirka.Implement.External.STMC.BAPI.Test
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ZBAPI_PRODORD_GET_LIST_YJ", Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZBAPI_PRODORD_GET_LIST_YJ : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ZbapiProdordGetListYjOperationCompleted;

        /// <remarks/>
        public ZBAPI_PRODORD_GET_LIST_YJ()
        {
            this.Url = "http://sapserver.sh-ctmc.com:8000/sap/bc/srt/rfc/sap/zbapi_prodord_get_list_yj/32" +
                "2/zbapi_prodord_get_list_yj/zbapi_prodord_get_list_yj";
        }

        /// <remarks/>
        public event ZbapiProdordGetListYjCompletedEventHandler ZbapiProdordGetListYjCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", ResponseNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Return", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bapiret2 ZbapiProdordGetListYj(
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string CollectiveOrder,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string Maktx,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiOrderMaterialRange[] MaterialRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderMrpCntrlRange[] MrpCntrlRange,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string OrderFinishBegin,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string OrderFinishEnd,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiOrderHeader1[] OrderHeader,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiPpOrderrange[] OrderNumberRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderPrioRange[] OrderPrioRange,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string OrderStartBegin,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string OrderStartEnd,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderOrderTypeRange[] OrderTypeRange,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] int Pagecurrent,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool PagecurrentSpecified,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] int Pagerows,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool PagerowsSpecified,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderPlanplantRange[] PlanplantRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderProdSchedRange[] ProdSchedRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderProdplantRange[] ProdplantRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderSalesOrdItmRange[] SalesOrdItmRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiOrderSalesOrdRange[] SalesOrdRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref OrderSeqNoRange[] SeqNoRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiPpStatus[] StatusRange,
                    [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZbapiOrderWbsElementRange[] WbsElementRange,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] string Wempf,
                    [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] out int Totalrows)
        {
            object[] results = this.Invoke("ZbapiProdordGetListYj", new object[] {
                        CollectiveOrder,
                        Maktx,
                        MaterialRange,
                        MrpCntrlRange,
                        OrderFinishBegin,
                        OrderFinishEnd,
                        OrderHeader,
                        OrderNumberRange,
                        OrderPrioRange,
                        OrderStartBegin,
                        OrderStartEnd,
                        OrderTypeRange,
                        Pagecurrent,
                        PagecurrentSpecified,
                        Pagerows,
                        PagerowsSpecified,
                        PlanplantRange,
                        ProdSchedRange,
                        ProdplantRange,
                        SalesOrdItmRange,
                        SalesOrdRange,
                        SeqNoRange,
                        StatusRange,
                        WbsElementRange,
                        Wempf});
            MaterialRange = ((ZbapiOrderMaterialRange[])(results[1]));
            MrpCntrlRange = ((OrderMrpCntrlRange[])(results[2]));
            OrderHeader = ((ZbapiOrderHeader1[])(results[3]));
            OrderNumberRange = ((ZbapiPpOrderrange[])(results[4]));
            OrderPrioRange = ((OrderPrioRange[])(results[5]));
            OrderTypeRange = ((OrderOrderTypeRange[])(results[6]));
            PlanplantRange = ((OrderPlanplantRange[])(results[7]));
            ProdSchedRange = ((OrderProdSchedRange[])(results[8]));
            ProdplantRange = ((OrderProdplantRange[])(results[9]));
            SalesOrdItmRange = ((OrderSalesOrdItmRange[])(results[10]));
            SalesOrdRange = ((ZbapiOrderSalesOrdRange[])(results[11]));
            SeqNoRange = ((OrderSeqNoRange[])(results[12]));
            StatusRange = ((ZbapiPpStatus[])(results[13]));
            WbsElementRange = ((ZbapiOrderWbsElementRange[])(results[14]));
            Totalrows = ((int)(results[15]));
            return ((Bapiret2)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginZbapiProdordGetListYj(
                    string CollectiveOrder,
                    string Maktx,
                    ZbapiOrderMaterialRange[] MaterialRange,
                    OrderMrpCntrlRange[] MrpCntrlRange,
                    string OrderFinishBegin,
                    string OrderFinishEnd,
                    ZbapiOrderHeader1[] OrderHeader,
                    ZbapiPpOrderrange[] OrderNumberRange,
                    OrderPrioRange[] OrderPrioRange,
                    string OrderStartBegin,
                    string OrderStartEnd,
                    OrderOrderTypeRange[] OrderTypeRange,
                    int Pagecurrent,
                    bool PagecurrentSpecified,
                    int Pagerows,
                    bool PagerowsSpecified,
                    OrderPlanplantRange[] PlanplantRange,
                    OrderProdSchedRange[] ProdSchedRange,
                    OrderProdplantRange[] ProdplantRange,
                    OrderSalesOrdItmRange[] SalesOrdItmRange,
                    ZbapiOrderSalesOrdRange[] SalesOrdRange,
                    OrderSeqNoRange[] SeqNoRange,
                    ZbapiPpStatus[] StatusRange,
                    ZbapiOrderWbsElementRange[] WbsElementRange,
                    string Wempf,
                    System.AsyncCallback callback,
                    object asyncState)
        {
            return this.BeginInvoke("ZbapiProdordGetListYj", new object[] {
                        CollectiveOrder,
                        Maktx,
                        MaterialRange,
                        MrpCntrlRange,
                        OrderFinishBegin,
                        OrderFinishEnd,
                        OrderHeader,
                        OrderNumberRange,
                        OrderPrioRange,
                        OrderStartBegin,
                        OrderStartEnd,
                        OrderTypeRange,
                        Pagecurrent,
                        PagecurrentSpecified,
                        Pagerows,
                        PagerowsSpecified,
                        PlanplantRange,
                        ProdSchedRange,
                        ProdplantRange,
                        SalesOrdItmRange,
                        SalesOrdRange,
                        SeqNoRange,
                        StatusRange,
                        WbsElementRange,
                        Wempf}, callback, asyncState);
        }

        /// <remarks/>
        public Bapiret2 EndZbapiProdordGetListYj(
                    System.IAsyncResult asyncResult,
                    out ZbapiOrderMaterialRange[] MaterialRange,
                    out OrderMrpCntrlRange[] MrpCntrlRange,
                    out ZbapiOrderHeader1[] OrderHeader,
                    out ZbapiPpOrderrange[] OrderNumberRange,
                    out OrderPrioRange[] OrderPrioRange,
                    out OrderOrderTypeRange[] OrderTypeRange,
                    out OrderPlanplantRange[] PlanplantRange,
                    out OrderProdSchedRange[] ProdSchedRange,
                    out OrderProdplantRange[] ProdplantRange,
                    out OrderSalesOrdItmRange[] SalesOrdItmRange,
                    out ZbapiOrderSalesOrdRange[] SalesOrdRange,
                    out OrderSeqNoRange[] SeqNoRange,
                    out ZbapiPpStatus[] StatusRange,
                    out ZbapiOrderWbsElementRange[] WbsElementRange,
                    out int Totalrows)
        {
            object[] results = this.EndInvoke(asyncResult);
            MaterialRange = ((ZbapiOrderMaterialRange[])(results[1]));
            MrpCntrlRange = ((OrderMrpCntrlRange[])(results[2]));
            OrderHeader = ((ZbapiOrderHeader1[])(results[3]));
            OrderNumberRange = ((ZbapiPpOrderrange[])(results[4]));
            OrderPrioRange = ((OrderPrioRange[])(results[5]));
            OrderTypeRange = ((OrderOrderTypeRange[])(results[6]));
            PlanplantRange = ((OrderPlanplantRange[])(results[7]));
            ProdSchedRange = ((OrderProdSchedRange[])(results[8]));
            ProdplantRange = ((OrderProdplantRange[])(results[9]));
            SalesOrdItmRange = ((OrderSalesOrdItmRange[])(results[10]));
            SalesOrdRange = ((ZbapiOrderSalesOrdRange[])(results[11]));
            SeqNoRange = ((OrderSeqNoRange[])(results[12]));
            StatusRange = ((ZbapiPpStatus[])(results[13]));
            WbsElementRange = ((ZbapiOrderWbsElementRange[])(results[14]));
            Totalrows = ((int)(results[15]));
            return ((Bapiret2)(results[0]));
        }

        /// <remarks/>
        public void ZbapiProdordGetListYjAsync(
                    string CollectiveOrder,
                    string Maktx,
                    ZbapiOrderMaterialRange[] MaterialRange,
                    OrderMrpCntrlRange[] MrpCntrlRange,
                    string OrderFinishBegin,
                    string OrderFinishEnd,
                    ZbapiOrderHeader1[] OrderHeader,
                    ZbapiPpOrderrange[] OrderNumberRange,
                    OrderPrioRange[] OrderPrioRange,
                    string OrderStartBegin,
                    string OrderStartEnd,
                    OrderOrderTypeRange[] OrderTypeRange,
                    int Pagecurrent,
                    bool PagecurrentSpecified,
                    int Pagerows,
                    bool PagerowsSpecified,
                    OrderPlanplantRange[] PlanplantRange,
                    OrderProdSchedRange[] ProdSchedRange,
                    OrderProdplantRange[] ProdplantRange,
                    OrderSalesOrdItmRange[] SalesOrdItmRange,
                    ZbapiOrderSalesOrdRange[] SalesOrdRange,
                    OrderSeqNoRange[] SeqNoRange,
                    ZbapiPpStatus[] StatusRange,
                    ZbapiOrderWbsElementRange[] WbsElementRange,
                    string Wempf)
        {
            this.ZbapiProdordGetListYjAsync(CollectiveOrder, Maktx, MaterialRange, MrpCntrlRange, OrderFinishBegin, OrderFinishEnd, OrderHeader, OrderNumberRange, OrderPrioRange, OrderStartBegin, OrderStartEnd, OrderTypeRange, Pagecurrent, PagecurrentSpecified, Pagerows, PagerowsSpecified, PlanplantRange, ProdSchedRange, ProdplantRange, SalesOrdItmRange, SalesOrdRange, SeqNoRange, StatusRange, WbsElementRange, Wempf, null);
        }

        /// <remarks/>
        public void ZbapiProdordGetListYjAsync(
                    string CollectiveOrder,
                    string Maktx,
                    ZbapiOrderMaterialRange[] MaterialRange,
                    OrderMrpCntrlRange[] MrpCntrlRange,
                    string OrderFinishBegin,
                    string OrderFinishEnd,
                    ZbapiOrderHeader1[] OrderHeader,
                    ZbapiPpOrderrange[] OrderNumberRange,
                    OrderPrioRange[] OrderPrioRange,
                    string OrderStartBegin,
                    string OrderStartEnd,
                    OrderOrderTypeRange[] OrderTypeRange,
                    int Pagecurrent,
                    bool PagecurrentSpecified,
                    int Pagerows,
                    bool PagerowsSpecified,
                    OrderPlanplantRange[] PlanplantRange,
                    OrderProdSchedRange[] ProdSchedRange,
                    OrderProdplantRange[] ProdplantRange,
                    OrderSalesOrdItmRange[] SalesOrdItmRange,
                    ZbapiOrderSalesOrdRange[] SalesOrdRange,
                    OrderSeqNoRange[] SeqNoRange,
                    ZbapiPpStatus[] StatusRange,
                    ZbapiOrderWbsElementRange[] WbsElementRange,
                    string Wempf,
                    object userState)
        {
            if ((this.ZbapiProdordGetListYjOperationCompleted == null))
            {
                this.ZbapiProdordGetListYjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZbapiProdordGetListYjOperationCompleted);
            }
            this.InvokeAsync("ZbapiProdordGetListYj", new object[] {
                        CollectiveOrder,
                        Maktx,
                        MaterialRange,
                        MrpCntrlRange,
                        OrderFinishBegin,
                        OrderFinishEnd,
                        OrderHeader,
                        OrderNumberRange,
                        OrderPrioRange,
                        OrderStartBegin,
                        OrderStartEnd,
                        OrderTypeRange,
                        Pagecurrent,
                        PagecurrentSpecified,
                        Pagerows,
                        PagerowsSpecified,
                        PlanplantRange,
                        ProdSchedRange,
                        ProdplantRange,
                        SalesOrdItmRange,
                        SalesOrdRange,
                        SeqNoRange,
                        StatusRange,
                        WbsElementRange,
                        Wempf}, this.ZbapiProdordGetListYjOperationCompleted, userState);
        }

        private void OnZbapiProdordGetListYjOperationCompleted(object arg)
        {
            if ((this.ZbapiProdordGetListYjCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZbapiProdordGetListYjCompleted(this, new ZbapiProdordGetListYjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiOrderMaterialRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        private string highExternalField;

        private string highGuidField;

        private string highVersionField;

        private string lowExternalField;

        private string lowGuidField;

        private string lowVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HighExternal
        {
            get
            {
                return this.highExternalField;
            }
            set
            {
                this.highExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HighGuid
        {
            get
            {
                return this.highGuidField;
            }
            set
            {
                this.highGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HighVersion
        {
            get
            {
                return this.highVersionField;
            }
            set
            {
                this.highVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LowExternal
        {
            get
            {
                return this.lowExternalField;
            }
            set
            {
                this.lowExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LowGuid
        {
            get
            {
                return this.lowGuidField;
            }
            set
            {
                this.lowGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LowVersion
        {
            get
            {
                return this.lowVersionField;
            }
            set
            {
                this.lowVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiOrderWbsElementRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiPpStatus
    {

        private string statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderSeqNoRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiOrderSalesOrdRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderSalesOrdItmRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderProdplantRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderProdSchedRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderPlanplantRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderOrderTypeRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderPrioRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiPpOrderrange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbapiOrderHeader1
    {

        private string orderNumberField;

        private string productionPlantField;

        private string mrpControllerField;

        private string productionSchedulerField;

        private string materialField;

        private string explDateField;

        private string routingNoField;

        private string reservationNumberField;

        private string schedReleaseDateField;

        private string actualReleaseDateField;

        private string finishDateField;

        private string startDateField;

        private string productionFinishDateField;

        private string productionStartDateField;

        private string actualStartDateField;

        private string actualFinishDateField;

        private decimal scrapField;

        private decimal targetQuantityField;

        private string unitField;

        private string unitIsoField;

        private string priorityField;

        private string orderTypeField;

        private string enteredByField;

        private string enterDateField;

        private string deletionFlagField;

        private string wbsElementField;

        private string confNoField;

        private string confCntField;

        private string intObjNoField;

        private string schedFinTimeField;

        private string schedStartTimeField;

        private string collectiveOrderField;

        private string orderSeqNoField;

        private string finishTimeField;

        private string startTimeField;

        private string actualStartTimeField;

        private string leadingOrderField;

        private string salesOrderField;

        private string salesOrderItemField;

        private string prodSchedProfileField;

        private string materialTextField;

        private string systemStatusField;

        private decimal confirmedQuantityField;

        private string planPlantField;

        private string batchField;

        private string materialExternalField;

        private string materialGuidField;

        private string materialVersionField;

        private string aufkAenamField;

        private string aufkAedatField;

        private string aufkPhas0Field;

        private string aufkPhas1Field;

        private string aufkPhas2Field;

        private string aufkPhas3Field;

        private string abladField;

        private string wempfField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionPlant
        {
            get
            {
                return this.productionPlantField;
            }
            set
            {
                this.productionPlantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MrpController
        {
            get
            {
                return this.mrpControllerField;
            }
            set
            {
                this.mrpControllerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionScheduler
        {
            get
            {
                return this.productionSchedulerField;
            }
            set
            {
                this.productionSchedulerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExplDate
        {
            get
            {
                return this.explDateField;
            }
            set
            {
                this.explDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RoutingNo
        {
            get
            {
                return this.routingNoField;
            }
            set
            {
                this.routingNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReservationNumber
        {
            get
            {
                return this.reservationNumberField;
            }
            set
            {
                this.reservationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SchedReleaseDate
        {
            get
            {
                return this.schedReleaseDateField;
            }
            set
            {
                this.schedReleaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActualReleaseDate
        {
            get
            {
                return this.actualReleaseDateField;
            }
            set
            {
                this.actualReleaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinishDate
        {
            get
            {
                return this.finishDateField;
            }
            set
            {
                this.finishDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionFinishDate
        {
            get
            {
                return this.productionFinishDateField;
            }
            set
            {
                this.productionFinishDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionStartDate
        {
            get
            {
                return this.productionStartDateField;
            }
            set
            {
                this.productionStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActualStartDate
        {
            get
            {
                return this.actualStartDateField;
            }
            set
            {
                this.actualStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActualFinishDate
        {
            get
            {
                return this.actualFinishDateField;
            }
            set
            {
                this.actualFinishDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Scrap
        {
            get
            {
                return this.scrapField;
            }
            set
            {
                this.scrapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TargetQuantity
        {
            get
            {
                return this.targetQuantityField;
            }
            set
            {
                this.targetQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitIso
        {
            get
            {
                return this.unitIsoField;
            }
            set
            {
                this.unitIsoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EnteredBy
        {
            get
            {
                return this.enteredByField;
            }
            set
            {
                this.enteredByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EnterDate
        {
            get
            {
                return this.enterDateField;
            }
            set
            {
                this.enterDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeletionFlag
        {
            get
            {
                return this.deletionFlagField;
            }
            set
            {
                this.deletionFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WbsElement
        {
            get
            {
                return this.wbsElementField;
            }
            set
            {
                this.wbsElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConfNo
        {
            get
            {
                return this.confNoField;
            }
            set
            {
                this.confNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConfCnt
        {
            get
            {
                return this.confCntField;
            }
            set
            {
                this.confCntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntObjNo
        {
            get
            {
                return this.intObjNoField;
            }
            set
            {
                this.intObjNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SchedFinTime
        {
            get
            {
                return this.schedFinTimeField;
            }
            set
            {
                this.schedFinTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SchedStartTime
        {
            get
            {
                return this.schedStartTimeField;
            }
            set
            {
                this.schedStartTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CollectiveOrder
        {
            get
            {
                return this.collectiveOrderField;
            }
            set
            {
                this.collectiveOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderSeqNo
        {
            get
            {
                return this.orderSeqNoField;
            }
            set
            {
                this.orderSeqNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinishTime
        {
            get
            {
                return this.finishTimeField;
            }
            set
            {
                this.finishTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActualStartTime
        {
            get
            {
                return this.actualStartTimeField;
            }
            set
            {
                this.actualStartTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LeadingOrder
        {
            get
            {
                return this.leadingOrderField;
            }
            set
            {
                this.leadingOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesOrder
        {
            get
            {
                return this.salesOrderField;
            }
            set
            {
                this.salesOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesOrderItem
        {
            get
            {
                return this.salesOrderItemField;
            }
            set
            {
                this.salesOrderItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProdSchedProfile
        {
            get
            {
                return this.prodSchedProfileField;
            }
            set
            {
                this.prodSchedProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialText
        {
            get
            {
                return this.materialTextField;
            }
            set
            {
                this.materialTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SystemStatus
        {
            get
            {
                return this.systemStatusField;
            }
            set
            {
                this.systemStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ConfirmedQuantity
        {
            get
            {
                return this.confirmedQuantityField;
            }
            set
            {
                this.confirmedQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlanPlant
        {
            get
            {
                return this.planPlantField;
            }
            set
            {
                this.planPlantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialExternal
        {
            get
            {
                return this.materialExternalField;
            }
            set
            {
                this.materialExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialGuid
        {
            get
            {
                return this.materialGuidField;
            }
            set
            {
                this.materialGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialVersion
        {
            get
            {
                return this.materialVersionField;
            }
            set
            {
                this.materialVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkAenam
        {
            get
            {
                return this.aufkAenamField;
            }
            set
            {
                this.aufkAenamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkAedat
        {
            get
            {
                return this.aufkAedatField;
            }
            set
            {
                this.aufkAedatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkPhas0
        {
            get
            {
                return this.aufkPhas0Field;
            }
            set
            {
                this.aufkPhas0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkPhas1
        {
            get
            {
                return this.aufkPhas1Field;
            }
            set
            {
                this.aufkPhas1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkPhas2
        {
            get
            {
                return this.aufkPhas2Field;
            }
            set
            {
                this.aufkPhas2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AufkPhas3
        {
            get
            {
                return this.aufkPhas3Field;
            }
            set
            {
                this.aufkPhas3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ablad
        {
            get
            {
                return this.abladField;
            }
            set
            {
                this.abladField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Wempf
        {
            get
            {
                return this.wempfField;
            }
            set
            {
                this.wempfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class OrderMrpCntrlRange
    {

        private string signField;

        private string optionField;

        private string lowField;

        private string highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string High
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ZbapiProdordGetListYjCompletedEventHandler(object sender, ZbapiProdordGetListYjCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZbapiProdordGetListYjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ZbapiProdordGetListYjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Bapiret2 Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Bapiret2)(this.results[0]));
            }
        }

        /// <remarks/>
        public ZbapiOrderMaterialRange[] MaterialRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiOrderMaterialRange[])(this.results[1]));
            }
        }

        /// <remarks/>
        public OrderMrpCntrlRange[] MrpCntrlRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderMrpCntrlRange[])(this.results[2]));
            }
        }

        /// <remarks/>
        public ZbapiOrderHeader1[] OrderHeader
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiOrderHeader1[])(this.results[3]));
            }
        }

        /// <remarks/>
        public ZbapiPpOrderrange[] OrderNumberRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiPpOrderrange[])(this.results[4]));
            }
        }

        /// <remarks/>
        public OrderPrioRange[] OrderPrioRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderPrioRange[])(this.results[5]));
            }
        }

        /// <remarks/>
        public OrderOrderTypeRange[] OrderTypeRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderOrderTypeRange[])(this.results[6]));
            }
        }

        /// <remarks/>
        public OrderPlanplantRange[] PlanplantRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderPlanplantRange[])(this.results[7]));
            }
        }

        /// <remarks/>
        public OrderProdSchedRange[] ProdSchedRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderProdSchedRange[])(this.results[8]));
            }
        }

        /// <remarks/>
        public OrderProdplantRange[] ProdplantRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderProdplantRange[])(this.results[9]));
            }
        }

        /// <remarks/>
        public OrderSalesOrdItmRange[] SalesOrdItmRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderSalesOrdItmRange[])(this.results[10]));
            }
        }

        /// <remarks/>
        public ZbapiOrderSalesOrdRange[] SalesOrdRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiOrderSalesOrdRange[])(this.results[11]));
            }
        }

        /// <remarks/>
        public OrderSeqNoRange[] SeqNoRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderSeqNoRange[])(this.results[12]));
            }
        }

        /// <remarks/>
        public ZbapiPpStatus[] StatusRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiPpStatus[])(this.results[13]));
            }
        }

        /// <remarks/>
        public ZbapiOrderWbsElementRange[] WbsElementRange
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZbapiOrderWbsElementRange[])(this.results[14]));
            }
        }

        /// <remarks/>
        public int Totalrows
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[15]));
            }
        }
    }
}
