//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace Etupirka.Implement.External.STMC.BAPI.Test
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ZMM_PO_WS", Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZMM_PO_WS : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ZmmFunPoGrOperationCompleted;

        private System.Threading.SendOrPostCallback ZmmFunPoCreateOperationCompleted;

        /// <remarks/>
        public ZMM_PO_WS()
        {
            this.Url = "http://sapserver.sh-ctmc.com:8000/sap/bc/srt/rfc/sap/zmm_po_ws/322/zmm_po_ws/zmm_" +
                "po_ws";
        }

        /// <remarks/>
        public event ZmmFunPoGrCompletedEventHandler ZmmFunPoGrCompleted;

        /// <remarks/>
        public event ZmmFunPoCreateCompletedEventHandler ZmmFunPoCreateCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", ResponseNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Mthead", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bapi2017GmHeadRet ZmmFunPoGr([System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref Bapiret2[] Errmsg, [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref Bapi2017GmItemCreate[] Pcitab)
        {
            object[] results = this.Invoke("ZmmFunPoGr", new object[] {
                        Errmsg,
                        Pcitab});
            Errmsg = ((Bapiret2[])(results[1]));
            Pcitab = ((Bapi2017GmItemCreate[])(results[2]));
            return ((Bapi2017GmHeadRet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginZmmFunPoGr(Bapiret2[] Errmsg, Bapi2017GmItemCreate[] Pcitab, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ZmmFunPoGr", new object[] {
                        Errmsg,
                        Pcitab}, callback, asyncState);
        }

        /// <remarks/>
        public Bapi2017GmHeadRet EndZmmFunPoGr(System.IAsyncResult asyncResult, out Bapiret2[] Errmsg, out Bapi2017GmItemCreate[] Pcitab)
        {
            object[] results = this.EndInvoke(asyncResult);
            Errmsg = ((Bapiret2[])(results[1]));
            Pcitab = ((Bapi2017GmItemCreate[])(results[2]));
            return ((Bapi2017GmHeadRet)(results[0]));
        }

        /// <remarks/>
        public void ZmmFunPoGrAsync(Bapiret2[] Errmsg, Bapi2017GmItemCreate[] Pcitab)
        {
            this.ZmmFunPoGrAsync(Errmsg, Pcitab, null);
        }

        /// <remarks/>
        public void ZmmFunPoGrAsync(Bapiret2[] Errmsg, Bapi2017GmItemCreate[] Pcitab, object userState)
        {
            if ((this.ZmmFunPoGrOperationCompleted == null))
            {
                this.ZmmFunPoGrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmmFunPoGrOperationCompleted);
            }
            this.InvokeAsync("ZmmFunPoGr", new object[] {
                        Errmsg,
                        Pcitab}, this.ZmmFunPoGrOperationCompleted, userState);
        }

        private void OnZmmFunPoGrOperationCompleted(object arg)
        {
            if ((this.ZmmFunPoGrCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZmmFunPoGrCompleted(this, new ZmmFunPoGrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", ResponseNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Ponumber", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZmmFunPoCreate([System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZncrKeyvalue[] GtOut, [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref Bapiret2[] Return, [System.Xml.Serialization.XmlArrayAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] ref ZmmPodata[] Zpodata)
        {
            object[] results = this.Invoke("ZmmFunPoCreate", new object[] {
                        GtOut,
                        Return,
                        Zpodata});
            GtOut = ((ZncrKeyvalue[])(results[1]));
            Return = ((Bapiret2[])(results[2]));
            Zpodata = ((ZmmPodata[])(results[3]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginZmmFunPoCreate(ZncrKeyvalue[] GtOut, Bapiret2[] Return, ZmmPodata[] Zpodata, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ZmmFunPoCreate", new object[] {
                        GtOut,
                        Return,
                        Zpodata}, callback, asyncState);
        }

        /// <remarks/>
        public string EndZmmFunPoCreate(System.IAsyncResult asyncResult, out ZncrKeyvalue[] GtOut, out Bapiret2[] Return, out ZmmPodata[] Zpodata)
        {
            object[] results = this.EndInvoke(asyncResult);
            GtOut = ((ZncrKeyvalue[])(results[1]));
            Return = ((Bapiret2[])(results[2]));
            Zpodata = ((ZmmPodata[])(results[3]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ZmmFunPoCreateAsync(ZncrKeyvalue[] GtOut, Bapiret2[] Return, ZmmPodata[] Zpodata)
        {
            this.ZmmFunPoCreateAsync(GtOut, Return, Zpodata, null);
        }

        /// <remarks/>
        public void ZmmFunPoCreateAsync(ZncrKeyvalue[] GtOut, Bapiret2[] Return, ZmmPodata[] Zpodata, object userState)
        {
            if ((this.ZmmFunPoCreateOperationCompleted == null))
            {
                this.ZmmFunPoCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmmFunPoCreateOperationCompleted);
            }
            this.InvokeAsync("ZmmFunPoCreate", new object[] {
                        GtOut,
                        Return,
                        Zpodata}, this.ZmmFunPoCreateOperationCompleted, userState);
        }

        private void OnZmmFunPoCreateOperationCompleted(object arg)
        {
            if ((this.ZmmFunPoCreateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZmmFunPoCreateCompleted(this, new ZmmFunPoCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2
    {

        private string typeField;

        private string idField;

        private string numberField;

        private string messageField;

        private string logNoField;

        private string logMsgNoField;

        private string messageV1Field;

        private string messageV2Field;

        private string messageV3Field;

        private string messageV4Field;

        private string parameterField;

        private int rowField;

        private string fieldField;

        private string systemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LogNo
        {
            get
            {
                return this.logNoField;
            }
            set
            {
                this.logNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LogMsgNo
        {
            get
            {
                return this.logMsgNoField;
            }
            set
            {
                this.logMsgNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageV1
        {
            get
            {
                return this.messageV1Field;
            }
            set
            {
                this.messageV1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageV2
        {
            get
            {
                return this.messageV2Field;
            }
            set
            {
                this.messageV2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageV3
        {
            get
            {
                return this.messageV3Field;
            }
            set
            {
                this.messageV3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageV4
        {
            get
            {
                return this.messageV4Field;
            }
            set
            {
                this.messageV4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string System
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmPodata
    {

        private string bsartField;

        private string lifnrField;

        private string ekorgField;

        private string ekgrpField;

        private string bukrsField;

        private string ihrezField;

        private string ebelpField;

        private string knttpField;

        private string matnrField;

        private string txz01Field;

        private decimal mengeField;

        private string meinsField;

        private string eeindField;

        private decimal netprField;

        private string waersField;

        private string matklField;

        private string werksField;

        private string bednrField;

        private string afnamField;

        private string mwskzField;

        private string saktoField;

        private string kostlField;

        private string anln1Field;

        private string aufnrField;

        private string str1Field;

        private string str2Field;

        private string str3Field;

        private string bstaeField;

        private string preqnoField;

        private string preqitemField;

        private string epstypField;

        private string wbsElementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bsart
        {
            get
            {
                return this.bsartField;
            }
            set
            {
                this.bsartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lifnr
        {
            get
            {
                return this.lifnrField;
            }
            set
            {
                this.lifnrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ekorg
        {
            get
            {
                return this.ekorgField;
            }
            set
            {
                this.ekorgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ekgrp
        {
            get
            {
                return this.ekgrpField;
            }
            set
            {
                this.ekgrpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bukrs
        {
            get
            {
                return this.bukrsField;
            }
            set
            {
                this.bukrsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ihrez
        {
            get
            {
                return this.ihrezField;
            }
            set
            {
                this.ihrezField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ebelp
        {
            get
            {
                return this.ebelpField;
            }
            set
            {
                this.ebelpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Knttp
        {
            get
            {
                return this.knttpField;
            }
            set
            {
                this.knttpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Matnr
        {
            get
            {
                return this.matnrField;
            }
            set
            {
                this.matnrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Txz01
        {
            get
            {
                return this.txz01Field;
            }
            set
            {
                this.txz01Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Menge
        {
            get
            {
                return this.mengeField;
            }
            set
            {
                this.mengeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Meins
        {
            get
            {
                return this.meinsField;
            }
            set
            {
                this.meinsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Eeind
        {
            get
            {
                return this.eeindField;
            }
            set
            {
                this.eeindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Netpr
        {
            get
            {
                return this.netprField;
            }
            set
            {
                this.netprField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers
        {
            get
            {
                return this.waersField;
            }
            set
            {
                this.waersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Matkl
        {
            get
            {
                return this.matklField;
            }
            set
            {
                this.matklField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Werks
        {
            get
            {
                return this.werksField;
            }
            set
            {
                this.werksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bednr
        {
            get
            {
                return this.bednrField;
            }
            set
            {
                this.bednrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Afnam
        {
            get
            {
                return this.afnamField;
            }
            set
            {
                this.afnamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mwskz
        {
            get
            {
                return this.mwskzField;
            }
            set
            {
                this.mwskzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sakto
        {
            get
            {
                return this.saktoField;
            }
            set
            {
                this.saktoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kostl
        {
            get
            {
                return this.kostlField;
            }
            set
            {
                this.kostlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Anln1
        {
            get
            {
                return this.anln1Field;
            }
            set
            {
                this.anln1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aufnr
        {
            get
            {
                return this.aufnrField;
            }
            set
            {
                this.aufnrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Str1
        {
            get
            {
                return this.str1Field;
            }
            set
            {
                this.str1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Str2
        {
            get
            {
                return this.str2Field;
            }
            set
            {
                this.str2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Str3
        {
            get
            {
                return this.str3Field;
            }
            set
            {
                this.str3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bstae
        {
            get
            {
                return this.bstaeField;
            }
            set
            {
                this.bstaeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Preqno
        {
            get
            {
                return this.preqnoField;
            }
            set
            {
                this.preqnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Preqitem
        {
            get
            {
                return this.preqitemField;
            }
            set
            {
                this.preqitemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Epstyp
        {
            get
            {
                return this.epstypField;
            }
            set
            {
                this.epstypField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WbsElement
        {
            get
            {
                return this.wbsElementField;
            }
            set
            {
                this.wbsElementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZncrKeyvalue
    {

        private int idField;

        private string keyidField;

        private string valueField;

        private string selField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Keyid
        {
            get
            {
                return this.keyidField;
            }
            set
            {
                this.keyidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sel
        {
            get
            {
                return this.selField;
            }
            set
            {
                this.selField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapi2017GmHeadRet
    {

        private string matDocField;

        private string docYearField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatDoc
        {
            get
            {
                return this.matDocField;
            }
            set
            {
                this.matDocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocYear
        {
            get
            {
                return this.docYearField;
            }
            set
            {
                this.docYearField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapi2017GmItemCreate
    {

        private string materialField;

        private string plantField;

        private string stgeLocField;

        private string batchField;

        private string moveTypeField;

        private string stckTypeField;

        private string specStockField;

        private string vendorField;

        private string customerField;

        private string salesOrdField;

        private string sOrdItemField;

        private string schedLineField;

        private string valTypeField;

        private decimal entryQntField;

        private string entryUomField;

        private string entryUomIsoField;

        private decimal poPrQntField;

        private string orderprUnField;

        private string orderprUnIsoField;

        private string poNumberField;

        private string poItemField;

        private string shippingField;

        private string compShipField;

        private string noMoreGrField;

        private string itemTextField;

        private string grRcptField;

        private string unloadPtField;

        private string costcenterField;

        private string orderidField;

        private string orderItnoField;

        private string calcMotiveField;

        private string assetNoField;

        private string subNumberField;

        private string reservNoField;

        private string resItemField;

        private string resTypeField;

        private string withdrawnField;

        private string moveMatField;

        private string movePlantField;

        private string moveStlocField;

        private string moveBatchField;

        private string moveValTypeField;

        private string mvtIndField;

        private string moveReasField;

        private string rlEstKeyField;

        private string refDateField;

        private string costObjField;

        private string profitSegmNoField;

        private string profitCtrField;

        private string wbsElemField;

        private string networkField;

        private string activityField;

        private string partAcctField;

        private decimal amountLcField;

        private decimal amountSvField;

        private string refDocYrField;

        private string refDocField;

        private string refDocItField;

        private string expirydateField;

        private string prodDateField;

        private string fundField;

        private string fundsCtrField;

        private string cmmtItemField;

        private string valSalesOrdField;

        private string valSOrdItemField;

        private string valWbsElemField;

        private string glAccountField;

        private string indProposeQuanxField;

        private string xstobField;

        private string eanUpcField;

        private string delivNumbToSearchField;

        private string delivItemToSearchField;

        private string serialnoAutoNumberassignmentField;

        private string vendrbatchField;

        private string stgeTypeField;

        private string stgeBinField;

        private decimal suPlStck1Field;

        private decimal stUnQtyy1Field;

        private string stUnQtyy1IsoField;

        private string unittype1Field;

        private decimal suPlStck2Field;

        private decimal stUnQtyy2Field;

        private string stUnQtyy2IsoField;

        private string unittype2Field;

        private string stgeTypePcField;

        private string stgeBinPcField;

        private string noPstChgntField;

        private string grNumberField;

        private string stgeTypeStField;

        private string stgeBinStField;

        private string matdocTrCancelField;

        private string matitemTrCancelField;

        private string matyearTrCancelField;

        private string noTransferReqField;

        private string coBusprocField;

        private string acttypeField;

        private string supplVendField;

        private string materialExternalField;

        private string materialGuidField;

        private string materialVersionField;

        private string moveMatExternalField;

        private string moveMatGuidField;

        private string moveMatVersionField;

        private string funcAreaField;

        private string trPartBaField;

        private string parCompcoField;

        private string delivNumbField;

        private string delivItemField;

        private string nbSlipsField;

        private string nbSlipsxField;

        private string grRcptxField;

        private string unloadPtxField;

        private string specMvmtField;

        private string grantNbrField;

        private string cmmtItemLongField;

        private string funcAreaLongField;

        private string lineIdField;

        private string parentIdField;

        private string lineDepthField;

        private decimal quantityField;

        private string baseUomField;

        private string longnumField;

        private string budgetPeriodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeLoc
        {
            get
            {
                return this.stgeLocField;
            }
            set
            {
                this.stgeLocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveType
        {
            get
            {
                return this.moveTypeField;
            }
            set
            {
                this.moveTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StckType
        {
            get
            {
                return this.stckTypeField;
            }
            set
            {
                this.stckTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecStock
        {
            get
            {
                return this.specStockField;
            }
            set
            {
                this.specStockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesOrd
        {
            get
            {
                return this.salesOrdField;
            }
            set
            {
                this.salesOrdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOrdItem
        {
            get
            {
                return this.sOrdItemField;
            }
            set
            {
                this.sOrdItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SchedLine
        {
            get
            {
                return this.schedLineField;
            }
            set
            {
                this.schedLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValType
        {
            get
            {
                return this.valTypeField;
            }
            set
            {
                this.valTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal EntryQnt
        {
            get
            {
                return this.entryQntField;
            }
            set
            {
                this.entryQntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntryUom
        {
            get
            {
                return this.entryUomField;
            }
            set
            {
                this.entryUomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntryUomIso
        {
            get
            {
                return this.entryUomIsoField;
            }
            set
            {
                this.entryUomIsoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PoPrQnt
        {
            get
            {
                return this.poPrQntField;
            }
            set
            {
                this.poPrQntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderprUn
        {
            get
            {
                return this.orderprUnField;
            }
            set
            {
                this.orderprUnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderprUnIso
        {
            get
            {
                return this.orderprUnIsoField;
            }
            set
            {
                this.orderprUnIsoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PoNumber
        {
            get
            {
                return this.poNumberField;
            }
            set
            {
                this.poNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PoItem
        {
            get
            {
                return this.poItemField;
            }
            set
            {
                this.poItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shipping
        {
            get
            {
                return this.shippingField;
            }
            set
            {
                this.shippingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompShip
        {
            get
            {
                return this.compShipField;
            }
            set
            {
                this.compShipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoMoreGr
        {
            get
            {
                return this.noMoreGrField;
            }
            set
            {
                this.noMoreGrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemText
        {
            get
            {
                return this.itemTextField;
            }
            set
            {
                this.itemTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrRcpt
        {
            get
            {
                return this.grRcptField;
            }
            set
            {
                this.grRcptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnloadPt
        {
            get
            {
                return this.unloadPtField;
            }
            set
            {
                this.unloadPtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Costcenter
        {
            get
            {
                return this.costcenterField;
            }
            set
            {
                this.costcenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orderid
        {
            get
            {
                return this.orderidField;
            }
            set
            {
                this.orderidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderItno
        {
            get
            {
                return this.orderItnoField;
            }
            set
            {
                this.orderItnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalcMotive
        {
            get
            {
                return this.calcMotiveField;
            }
            set
            {
                this.calcMotiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetNo
        {
            get
            {
                return this.assetNoField;
            }
            set
            {
                this.assetNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubNumber
        {
            get
            {
                return this.subNumberField;
            }
            set
            {
                this.subNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReservNo
        {
            get
            {
                return this.reservNoField;
            }
            set
            {
                this.reservNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResItem
        {
            get
            {
                return this.resItemField;
            }
            set
            {
                this.resItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResType
        {
            get
            {
                return this.resTypeField;
            }
            set
            {
                this.resTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Withdrawn
        {
            get
            {
                return this.withdrawnField;
            }
            set
            {
                this.withdrawnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveMat
        {
            get
            {
                return this.moveMatField;
            }
            set
            {
                this.moveMatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MovePlant
        {
            get
            {
                return this.movePlantField;
            }
            set
            {
                this.movePlantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveStloc
        {
            get
            {
                return this.moveStlocField;
            }
            set
            {
                this.moveStlocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveBatch
        {
            get
            {
                return this.moveBatchField;
            }
            set
            {
                this.moveBatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveValType
        {
            get
            {
                return this.moveValTypeField;
            }
            set
            {
                this.moveValTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MvtInd
        {
            get
            {
                return this.mvtIndField;
            }
            set
            {
                this.mvtIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveReas
        {
            get
            {
                return this.moveReasField;
            }
            set
            {
                this.moveReasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RlEstKey
        {
            get
            {
                return this.rlEstKeyField;
            }
            set
            {
                this.rlEstKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefDate
        {
            get
            {
                return this.refDateField;
            }
            set
            {
                this.refDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostObj
        {
            get
            {
                return this.costObjField;
            }
            set
            {
                this.costObjField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProfitSegmNo
        {
            get
            {
                return this.profitSegmNoField;
            }
            set
            {
                this.profitSegmNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProfitCtr
        {
            get
            {
                return this.profitCtrField;
            }
            set
            {
                this.profitCtrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WbsElem
        {
            get
            {
                return this.wbsElemField;
            }
            set
            {
                this.wbsElemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Network
        {
            get
            {
                return this.networkField;
            }
            set
            {
                this.networkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartAcct
        {
            get
            {
                return this.partAcctField;
            }
            set
            {
                this.partAcctField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AmountLc
        {
            get
            {
                return this.amountLcField;
            }
            set
            {
                this.amountLcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AmountSv
        {
            get
            {
                return this.amountSvField;
            }
            set
            {
                this.amountSvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefDocYr
        {
            get
            {
                return this.refDocYrField;
            }
            set
            {
                this.refDocYrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefDoc
        {
            get
            {
                return this.refDocField;
            }
            set
            {
                this.refDocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefDocIt
        {
            get
            {
                return this.refDocItField;
            }
            set
            {
                this.refDocItField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expirydate
        {
            get
            {
                return this.expirydateField;
            }
            set
            {
                this.expirydateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProdDate
        {
            get
            {
                return this.prodDateField;
            }
            set
            {
                this.prodDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fund
        {
            get
            {
                return this.fundField;
            }
            set
            {
                this.fundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FundsCtr
        {
            get
            {
                return this.fundsCtrField;
            }
            set
            {
                this.fundsCtrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CmmtItem
        {
            get
            {
                return this.cmmtItemField;
            }
            set
            {
                this.cmmtItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValSalesOrd
        {
            get
            {
                return this.valSalesOrdField;
            }
            set
            {
                this.valSalesOrdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValSOrdItem
        {
            get
            {
                return this.valSOrdItemField;
            }
            set
            {
                this.valSOrdItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValWbsElem
        {
            get
            {
                return this.valWbsElemField;
            }
            set
            {
                this.valWbsElemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlAccount
        {
            get
            {
                return this.glAccountField;
            }
            set
            {
                this.glAccountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IndProposeQuanx
        {
            get
            {
                return this.indProposeQuanxField;
            }
            set
            {
                this.indProposeQuanxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Xstob
        {
            get
            {
                return this.xstobField;
            }
            set
            {
                this.xstobField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EanUpc
        {
            get
            {
                return this.eanUpcField;
            }
            set
            {
                this.eanUpcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DelivNumbToSearch
        {
            get
            {
                return this.delivNumbToSearchField;
            }
            set
            {
                this.delivNumbToSearchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DelivItemToSearch
        {
            get
            {
                return this.delivItemToSearchField;
            }
            set
            {
                this.delivItemToSearchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialnoAutoNumberassignment
        {
            get
            {
                return this.serialnoAutoNumberassignmentField;
            }
            set
            {
                this.serialnoAutoNumberassignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vendrbatch
        {
            get
            {
                return this.vendrbatchField;
            }
            set
            {
                this.vendrbatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeType
        {
            get
            {
                return this.stgeTypeField;
            }
            set
            {
                this.stgeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeBin
        {
            get
            {
                return this.stgeBinField;
            }
            set
            {
                this.stgeBinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SuPlStck1
        {
            get
            {
                return this.suPlStck1Field;
            }
            set
            {
                this.suPlStck1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal StUnQtyy1
        {
            get
            {
                return this.stUnQtyy1Field;
            }
            set
            {
                this.stUnQtyy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StUnQtyy1Iso
        {
            get
            {
                return this.stUnQtyy1IsoField;
            }
            set
            {
                this.stUnQtyy1IsoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unittype1
        {
            get
            {
                return this.unittype1Field;
            }
            set
            {
                this.unittype1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SuPlStck2
        {
            get
            {
                return this.suPlStck2Field;
            }
            set
            {
                this.suPlStck2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal StUnQtyy2
        {
            get
            {
                return this.stUnQtyy2Field;
            }
            set
            {
                this.stUnQtyy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StUnQtyy2Iso
        {
            get
            {
                return this.stUnQtyy2IsoField;
            }
            set
            {
                this.stUnQtyy2IsoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unittype2
        {
            get
            {
                return this.unittype2Field;
            }
            set
            {
                this.unittype2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeTypePc
        {
            get
            {
                return this.stgeTypePcField;
            }
            set
            {
                this.stgeTypePcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeBinPc
        {
            get
            {
                return this.stgeBinPcField;
            }
            set
            {
                this.stgeBinPcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoPstChgnt
        {
            get
            {
                return this.noPstChgntField;
            }
            set
            {
                this.noPstChgntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrNumber
        {
            get
            {
                return this.grNumberField;
            }
            set
            {
                this.grNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeTypeSt
        {
            get
            {
                return this.stgeTypeStField;
            }
            set
            {
                this.stgeTypeStField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StgeBinSt
        {
            get
            {
                return this.stgeBinStField;
            }
            set
            {
                this.stgeBinStField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatdocTrCancel
        {
            get
            {
                return this.matdocTrCancelField;
            }
            set
            {
                this.matdocTrCancelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatitemTrCancel
        {
            get
            {
                return this.matitemTrCancelField;
            }
            set
            {
                this.matitemTrCancelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatyearTrCancel
        {
            get
            {
                return this.matyearTrCancelField;
            }
            set
            {
                this.matyearTrCancelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoTransferReq
        {
            get
            {
                return this.noTransferReqField;
            }
            set
            {
                this.noTransferReqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CoBusproc
        {
            get
            {
                return this.coBusprocField;
            }
            set
            {
                this.coBusprocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Acttype
        {
            get
            {
                return this.acttypeField;
            }
            set
            {
                this.acttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplVend
        {
            get
            {
                return this.supplVendField;
            }
            set
            {
                this.supplVendField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialExternal
        {
            get
            {
                return this.materialExternalField;
            }
            set
            {
                this.materialExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialGuid
        {
            get
            {
                return this.materialGuidField;
            }
            set
            {
                this.materialGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialVersion
        {
            get
            {
                return this.materialVersionField;
            }
            set
            {
                this.materialVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveMatExternal
        {
            get
            {
                return this.moveMatExternalField;
            }
            set
            {
                this.moveMatExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveMatGuid
        {
            get
            {
                return this.moveMatGuidField;
            }
            set
            {
                this.moveMatGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoveMatVersion
        {
            get
            {
                return this.moveMatVersionField;
            }
            set
            {
                this.moveMatVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FuncArea
        {
            get
            {
                return this.funcAreaField;
            }
            set
            {
                this.funcAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrPartBa
        {
            get
            {
                return this.trPartBaField;
            }
            set
            {
                this.trPartBaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParCompco
        {
            get
            {
                return this.parCompcoField;
            }
            set
            {
                this.parCompcoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DelivNumb
        {
            get
            {
                return this.delivNumbField;
            }
            set
            {
                this.delivNumbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DelivItem
        {
            get
            {
                return this.delivItemField;
            }
            set
            {
                this.delivItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbSlips
        {
            get
            {
                return this.nbSlipsField;
            }
            set
            {
                this.nbSlipsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbSlipsx
        {
            get
            {
                return this.nbSlipsxField;
            }
            set
            {
                this.nbSlipsxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrRcptx
        {
            get
            {
                return this.grRcptxField;
            }
            set
            {
                this.grRcptxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnloadPtx
        {
            get
            {
                return this.unloadPtxField;
            }
            set
            {
                this.unloadPtxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecMvmt
        {
            get
            {
                return this.specMvmtField;
            }
            set
            {
                this.specMvmtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrantNbr
        {
            get
            {
                return this.grantNbrField;
            }
            set
            {
                this.grantNbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CmmtItemLong
        {
            get
            {
                return this.cmmtItemLongField;
            }
            set
            {
                this.cmmtItemLongField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FuncAreaLong
        {
            get
            {
                return this.funcAreaLongField;
            }
            set
            {
                this.funcAreaLongField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineId
        {
            get
            {
                return this.lineIdField;
            }
            set
            {
                this.lineIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineDepth
        {
            get
            {
                return this.lineDepthField;
            }
            set
            {
                this.lineDepthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BaseUom
        {
            get
            {
                return this.baseUomField;
            }
            set
            {
                this.baseUomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Longnum
        {
            get
            {
                return this.longnumField;
            }
            set
            {
                this.longnumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BudgetPeriod
        {
            get
            {
                return this.budgetPeriodField;
            }
            set
            {
                this.budgetPeriodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ZmmFunPoGrCompletedEventHandler(object sender, ZmmFunPoGrCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZmmFunPoGrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ZmmFunPoGrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Bapi2017GmHeadRet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Bapi2017GmHeadRet)(this.results[0]));
            }
        }

        /// <remarks/>
        public Bapiret2[] Errmsg
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Bapiret2[])(this.results[1]));
            }
        }

        /// <remarks/>
        public Bapi2017GmItemCreate[] Pcitab
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Bapi2017GmItemCreate[])(this.results[2]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ZmmFunPoCreateCompletedEventHandler(object sender, ZmmFunPoCreateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZmmFunPoCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ZmmFunPoCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }

        /// <remarks/>
        public ZncrKeyvalue[] GtOut
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZncrKeyvalue[])(this.results[1]));
            }
        }

        /// <remarks/>
        public Bapiret2[] Return
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Bapiret2[])(this.results[2]));
            }
        }

        /// <remarks/>
        public ZmmPodata[] Zpodata
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZmmPodata[])(this.results[3]));
            }
        }
    }
}
