// <auto-generated />
namespace Etupirka.EntityFramework.Manufacture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DispatchedWorker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DispatchedWorker));
        
        string IMigrationMetadata.Id
        {
            get { return "201703310253501_DispatchedWorker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
