// <auto-generated />
namespace Etupirka.EntityFramework.Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abp113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abp113));
        
        string IMigrationMetadata.Id
        {
            get { return "201612280718580_abp113"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
